### PR TITLE
Add SvelteKit edge example

### PR DESCRIPTION
**Pull request by geoffrich**
This is an example for an upcoming blog post. It also renames the other SvelteKit demo in the repo to be consistent with how SvelteKit is written out (SvelteKit, not Svelte Kit).

### CODE REVIEW

**Comment by chronark** [comment]
👍 thank you

while we're on the topic of conventions, in javascript the most common way of naming variables etc is `camelCase` instead of `snake_case`. 
It might confuse developers who are new to the language and distract experience ones, wdyt?

**Comment by geoffrich** [comment]
Hey! I chose snake case since that's how the default SvelteKit templates are written (e.g. see https://github.com/sveltejs/kit/blob/3d801d251aa4b35737da586771120c776ecf8c35/packages/create-svelte/templates/default/src/lib/form.ts#L64). But if you'd prefer camel case for this repo, I can make the switch -- just let me know.

**Comment by chronark** [comment]
Oh interesting... and weird :D
But If this is from an official template than my points are probably not valid, because svelte devs expect snake_case.

I have never used it myself. Is snake case common in svelte applications?

**Comment by geoffrich** [comment]
I'd say there's a mix of camel and snake case in the community. In general the maintainers prefer snake case (which is why the templates use it), but people in the community also use camel case.

So you could really argue for either 😄 I'm happy to go either way; the template started with snake case so that's what I chose.

**Comment by chronark** [comment]
OK thank you so much for explaining (and also the example)
Let's go with snake case

**Pull request merged**
